### ISSUE TITLE
tinyyolo

### ISSUE THREAD

**Issue by pliablepixels** [arunponnusamy/cvlib#3]
Thanks for this useful library. I'd love to see tiny yolo integration too

**Comment by arunponnusamy** [comment]
Hello @pliablepixels , glad that you are finding the library useful. I am currently working on adding tiny yolo. Will be out in the next release soon. Watch this space for updates. Cheers.

**Comment by AlexanderMelde** [comment]
Hey Arun, nice to see you are working on it, is there anything we could help you with? I would love to try out the tinyyolo version.

**Comment by rkantos** [comment]
I am also interested in tinyyolo.. also yolo9000… Should they just work if I change to the respective cfg & weights to either one?

**Comment by arunponnusamy** [comment]
Hi, I have added tiny yolo for real time object detection.  Just specify the model `yolov3-tiny` while calling the function `detect_common_objects( )`.  It is significantly fast but the detection accuracy / recall is very less compared to original `yolov3` version. Checkout the example here https://github.com/arunponnusamy/cvlib/blob/master/examples/object_detection_webcam_yolov3_tiny.py
