### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Tousama** [arunponnusamy/cvlib#34]

**Comment by Tousama** [comment]
![image](https://user-images.githubusercontent.com/16278872/74820295-d538af00-5312-11ea-8d2b-6c9eb06ff180.png)
![image](https://user-images.githubusercontent.com/16278872/74820350-eb466f80-5312-11ea-9199-9d4ca800a2ef.png)
I got an error like this. How can i fix?

**Comment by torgrimb** [comment]
Just ran the same code which is working on my machine on a fresh virtualenv (Anaconda). Long shot: pip install scipy?

**Comment by EthanWill059** [comment]
`pip install opencv-python tensorflow`

Try that
