### ISSUE TITLE
'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by NicholasCrets** [arunponnusamy/cvlib#52]
When I try to use a function, do i get the error:

Traceback (most recent call last):
  File "E:/python/test-object-detectie1.py", line 4, in <module>
    bbox, label, conf = cv.detect_common_objects('object_detection_input.jpg')
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\cvlib\object_detection.py", line 77, in detect_common_objects
    Height, Width = image.shape[:2]
AttributeError: 'str' object has no attribute 'shape'

Can someone help me?

**Comment by arunponnusamy** [comment]
You need to read the image before passing it to `detect_common_objects` function.
```
# read input image
image = cv2.imread('object_detection_input.jpg')

# apply object detection
bbox, label, conf = cv.detect_common_objects(image)
```
Checkout this complete [example](https://github.com/arunponnusamy/cvlib/blob/master/examples/object_detection.py).

**Comment by NicholasCrets** [comment]
As i try that, i get the second error:`Traceback (most recent call last):
  File "G:\SR4E1\test-object-detectie1.py", line 12, in <module>
    bbox, label, conf = cv.detect_common_objects(image)
  File "C:\Users\philippechristl\AppData\Local\Programs\Python\Python310\lib\site-packages\cvlib\object_detection.py", line 77, in detect_common_objects
    Height, Width = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
`

**Comment by arunponnusamy** [comment]
Make sure that you are giving the correct path to the input image while reading using `cv2.imread`. Try giving the complete path to the image. For example, if the image is in `SR4E1` folder, try using the path as below.
```
image = cv2.imread('G:\SR4E1\object_detection_input.jpg')
```
Checkout this [Colab notebook](https://pages.visiongeek.io/object-detection-cvlib) to learn more.

**Comment by arunponnusamy** [comment]
Can you share the complete code and input image you are using ? Let me try to reproduce this error on my end for debugging. Please share the version of OpenCV, cvlib and Python as well.

**Comment by NicholasCrets** [comment]
python version = 3.10.8
cvlib version = 0.2.7
OpenCV version = 1.0.0
image = [https://github.com/arunponnusamy/cvlib/blob/master/examples/images/object_detection_input.jpg](url)

`import cvlib as cv
from cvlib.object_detection import draw_bbox
import sys
import cv2

# read input image
image = cv2.imread(sys.argv[1])

# apply object detection
bbox, label, conf = cv.detect_common_objects(image)

print(bbox, label, conf)

# draw bounding box over detected objects
out = draw_bbox(image, bbox, label, conf)

# display output
# press any key to close window           
cv2.imshow("object_detection", out)
cv2.waitKey()

# save output
cv2.imwrite("object_detection.jpg", out)

# release resources
cv2.destroyAllWindows()`

**Comment by arunponnusamy** [comment]
What command are you using to run the code ?

**Comment by NicholasCrets** [comment]
python E:\SR4E1\test-object-detectie1.py E:\SR4E1\imeges\object_detection_input.jpg (on Windows 10)

**Comment by arunponnusamy** [comment]
It seems that there is issue in reading the image. Are you sure the path to the input image is correct ? 
The folder name is `images` or `imeges` ? Is that a typo ?

**Comment by NicholasCrets** [comment]
That is a typo. The folder name is `images`

**Comment by arunponnusamy** [comment]
Can you try running the command from the `SR4E1` folder ? 
```
cd E:\SR4E1\
python test-object-detectie1.py E:\SR4E1\images\object_detection_input.jpg
```

**Comment by NicholasCrets** [comment]
Still the same error ...

**Comment by NicholasCrets** [comment]
As i convert the images to PNG it's work! Thank you for helping me. (and for the easy to use libarty)
