### ISSUE TITLE
detect_face finds faces in the background with a greater confidence

### ISSUE THREAD

**Issue by leonvictor** [arunponnusamy/cvlib#8]
Hey, first of all, thanks for the great lib. I've been playing around with face detection on the [Mc-Master Pain Shoulder dataset](https://ieeexplore.ieee.org/document/5771462) to extract bounding boxes and am facing some issues.

In some cases, detect_faces returns multiple bounding boxes. No big deal, except that it gives a greater confidence to the wrongly detected background parts for no apparent reason.

![bm049t2aaaff217](https://user-images.githubusercontent.com/10499605/46790514-6e2ee180-cd3f-11e8-92d9-fe08c2f2f93d.png)

![marchepas](https://user-images.githubusercontent.com/10499605/46790403-24de9200-cd3f-11e8-9431-8219fbb76aca.png)

Any idea why this could be happening ? Or how I can detect mishaps like this one ? If you have any idea how I can fix this let me know, I'd be glad to contribute. 

Thanks

**Comment by arunponnusamy** [comment]
Hi @leonvictor , `detect_face( )`  function actually uses `resnet10` backbone with `ssd` object detection method. 
1. resnet10 is not so deep. It's a lightweight network.(That is why, it is able to run on real time input). So, it is not perfect. 
2. The model being used here is actually trained on data where face is at a distance from the camera. If the face is close to the camera, (ie) if the face is occupying larger part of the image, it will struggle to detect / will return multiple detections. I have experienced this myself.

In this case I would suggest to use the frontal face detector in `dlib`. If execution time is not an issue, you can try the cnn face detector in dlib. Checkout this [blog post](https://www.arunponnusamy.com/cnn-face-detector-dlib.html) to learn more.
